import { useMemo, useState } from 'react';
import { DatabaseIcon, Edit3Icon, PlusIcon, SearchIcon, Trash2Icon, WifiIcon } from 'lucide-react';
import { toast } from 'sonner';
import { LowcodeButton, Modal, PageShell, formatTime } from './LowcodeShared';

type SourceType = 'MySQL' | 'PostgreSQL' | 'Redis' | 'HTTP';
type Source = { id: string; name: string; type: SourceType; status: '正常' | '异常'; createdAt: string; host: string; port: string; user: string; password: string; database: string; baseUrl: string; headers: string };

const initialSources: Source[] = [
  { id: 'ds-1', name: '商城业务库', type: 'MySQL', status: '正常', createdAt: '2026-08-05 09:16:20', host: '10.20.8.15', port: '3306', user: 'mall_rw', password: '******', database: 'mall_prod', baseUrl: '', headers: '' },
  { id: 'ds-2', name: '用户中心库', type: 'PostgreSQL', status: '正常', createdAt: '2026-08-04 16:32:09', host: '10.20.8.21', port: '5432', user: 'user_service', password: '******', database: 'user_center', baseUrl: '', headers: '' },
  { id: 'ds-3', name: '会话缓存', type: 'Redis', status: '正常', createdAt: '2026-08-03 11:20:44', host: '10.20.8.18', port: '6379', user: '', password: '******', database: '0', baseUrl: '', headers: '' },
  { id: 'ds-4', name: '库存开放平台', type: 'HTTP', status: '异常', createdAt: '2026-08-02 08:48:30', host: '', port: '', user: '', password: '', database: '', baseUrl: 'https://inventory.example.com', headers: 'Authorization: Bearer {{token}}' },
];
const emptySource = (): Source => ({ id: '', name: '', type: 'MySQL', status: '正常', createdAt: '', host: '', port: '3306', user: '', password: '', database: '', baseUrl: '', headers: '' });

export default function DataSourcePage() {
  const [sources, setSources] = useState<Source[]>(initialSources);
  const [selected, setSelected] = useState<string[]>([]);
  const [keyword, setKeyword] = useState('');
  const [type, setType] = useState<'全部' | SourceType>('全部');
  const [sortDesc, setSortDesc] = useState(true);
  const [editing, setEditing] = useState<Source | null>(null);
  const [page, setPage] = useState(1);
  const filtered = useMemo(() => sources.filter(item => (type === '全部' || item.type === type) && item.name.toLowerCase().includes(keyword.toLowerCase())).sort((a, b) => sortDesc ? b.createdAt.localeCompare(a.createdAt) : a.createdAt.localeCompare(b.createdAt)), [sources, keyword, type, sortDesc]);
  const submit = () => {
    if (!editing) return;
    if (!editing.name.trim()) return toast.error('请填写数据源名称');
    if (editing.type === 'HTTP' && !editing.baseUrl.trim()) return toast.error('请填写 HTTP Base URL');
    if (editing.type !== 'HTTP' && (!editing.host.trim() || !editing.port.trim())) return toast.error('请填写主机与端口');
    if (editing.id) { setSources(prev => prev.map(item => item.id === editing.id ? editing : item)); toast.success('数据源已更新'); }
    else { setSources(prev => [{ ...editing, id: `ds-${Date.now()}`, createdAt: formatTime() }, ...prev]); toast.success('数据源已创建'); }
    setEditing(null);
  };
  const testConnection = (source: Source) => { toast.loading(`正在测试「${source.name}」连接…`, { id: `test-${source.id}` }); window.setTimeout(() => toast[source.status === '正常' ? 'success' : 'error'](source.status === '正常' ? '连接成功，响应耗时 38ms' : '连接失败，请检查网络与凭据', { id: `test-${source.id}` }), 650); };
  const deleteSource = (source: Source) => { if (window.confirm(`确定删除数据源「${source.name}」吗？`)) { setSources(prev => prev.filter(item => item.id !== source.id)); setSelected(prev => prev.filter(id => id !== source.id)); toast.success('数据源已删除'); } };
  const allSelected = filtered.length > 0 && filtered.every(source => selected.includes(source.id));
  return <PageShell title="数据源管理" description="统一维护数据库、缓存与 HTTP 数据源；可供接口编排与页面组件安全调用。" actions={<LowcodeButton primary onClick={() => setEditing(emptySource())}><PlusIcon size={14} />新增数据源</LowcodeButton>}>
    <section className="lc-card lc-table-card">
      <div className="lc-table-tools"><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><span style={{ position: 'relative' }}><SearchIcon size={14} style={{ position: 'absolute', left: 9, top: 9, color: 'var(--muted-foreground)' }} /><input className="lc-input" style={{ width: 220, paddingLeft: 29 }} value={keyword} placeholder="搜索数据源名称" onChange={event => { setKeyword(event.target.value); setPage(1); }} /></span><select className="lc-select" style={{ width: 130 }} value={type} onChange={event => setType(event.target.value as '全部' | SourceType)}><option>全部</option><option>MySQL</option><option>PostgreSQL</option><option>Redis</option><option>HTTP</option></select></div><div>{selected.length > 0 && <LowcodeButton danger onClick={() => { setSources(prev => prev.filter(item => !selected.includes(item.id))); setSelected([]); toast.success(`已删除 ${selected.length} 个数据源`); }}><Trash2Icon size={14} />批量删除（{selected.length}）</LowcodeButton>}</div></div>
      <div className="lc-table-wrap"><table className="lc-table"><thead><tr><th><input type="checkbox" checked={allSelected} onChange={event => setSelected(event.target.checked ? filtered.map(item => item.id) : [])} /></th><th>名称</th><th>类型</th><th>状态</th><th>连接信息</th><th style={{ cursor: 'pointer' }} onClick={() => setSortDesc(value => !value)}>创建时间 {sortDesc ? '↓' : '↑'}</th><th>操作</th></tr></thead><tbody>{filtered.map(source => <tr key={source.id}><td><input type="checkbox" checked={selected.includes(source.id)} onChange={event => setSelected(prev => event.target.checked ? [...prev, source.id] : prev.filter(id => id !== source.id))} /></td><td><span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontWeight: 600 }}><span style={{ display: 'grid', placeItems: 'center', width: 28, height: 28, borderRadius: 6, color: '#165DFF', background: '#e8f3ff' }}><DatabaseIcon size={14} /></span>{source.name}</span></td><td>{source.type}</td><td><span className={`lc-badge ${source.status === '正常' ? 'success' : 'warning'}`}>● {source.status}</span></td><td style={{ color: 'var(--muted-foreground)' }}>{source.type === 'HTTP' ? source.baseUrl : `${source.host}:${source.port} / ${source.database || '-'}`}</td><td>{source.createdAt}</td><td><button className="lc-link-btn" onClick={() => setEditing({ ...source })}><Edit3Icon size={13} /> 编辑</button><button className="lc-link-btn" onClick={() => testConnection(source)}><WifiIcon size={13} /> 测试</button><button className="lc-link-btn" style={{ color: '#F53F3F' }} onClick={() => deleteSource(source)}><Trash2Icon size={13} /> 删除</button></td></tr>)}{!filtered.length && <tr><td colSpan={7} style={{ height: 180, textAlign: 'center', color: 'var(--muted-foreground)' }}>暂无数据源，点击“新增数据源”完成首次配置。</td></tr>}</tbody></table></div><div className="lc-pagination"><span>共 {filtered.length} 条</span><LowcodeButton onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1}>上一页</LowcodeButton><span>第 {page} 页</span><LowcodeButton onClick={() => setPage(page + 1)} disabled={filtered.length < 10}>下一页</LowcodeButton></div>
    </section>
    <Modal title={editing?.id ? '编辑数据源' : '新增数据源'} open={Boolean(editing)} onClose={() => setEditing(null)} footer={<><LowcodeButton onClick={() => setEditing(null)}>取消</LowcodeButton><LowcodeButton primary onClick={submit}>保存</LowcodeButton></>}><div className="lc-field"><label className="lc-label">数据源名称 <span style={{ color: '#F53F3F' }}>*</span></label><input className="lc-input" value={editing?.name ?? ''} placeholder="例如：商城业务库" onChange={event => setEditing(prev => prev ? { ...prev, name: event.target.value } : prev)} /></div><div className="lc-field"><label className="lc-label">类型</label><select className="lc-select" value={editing?.type ?? 'MySQL'} onChange={event => setEditing(prev => prev ? { ...prev, type: event.target.value as SourceType, port: event.target.value === 'PostgreSQL' ? '5432' : event.target.value === 'Redis' ? '6379' : '3306' } : prev)}>{(['MySQL', 'PostgreSQL', 'Redis', 'HTTP'] as SourceType[]).map(item => <option key={item}>{item}</option>)}</select></div>{editing?.type === 'HTTP' ? <><div className="lc-field"><label className="lc-label">Base URL <span style={{ color: '#F53F3F' }}>*</span></label><input className="lc-input" value={editing.baseUrl} placeholder="https://api.example.com" onChange={event => setEditing(prev => prev ? { ...prev, baseUrl: event.target.value } : prev)} /></div><div className="lc-field"><label className="lc-label">默认 Header</label><textarea className="lc-textarea" value={editing.headers} placeholder="Authorization: Bearer {{token}}" onChange={event => setEditing(prev => prev ? { ...prev, headers: event.target.value } : prev)} /></div></> : <><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}><div className="lc-field"><label className="lc-label">主机 <span style={{ color: '#F53F3F' }}>*</span></label><input className="lc-input" value={editing?.host ?? ''} placeholder="10.0.0.1" onChange={event => setEditing(prev => prev ? { ...prev, host: event.target.value } : prev)} /></div><div className="lc-field"><label className="lc-label">端口 <span style={{ color: '#F53F3F' }}>*</span></label><input className="lc-input" value={editing?.port ?? ''} onChange={event => setEditing(prev => prev ? { ...prev, port: event.target.value } : prev)} /></div></div><div className="lc-field"><label className="lc-label">用户名</label><input className="lc-input" value={editing?.user ?? ''} onChange={event => setEditing(prev => prev ? { ...prev, user: event.target.value } : prev)} /></div><div className="lc-field"><label className="lc-label">密码</label><input className="lc-input" type="password" value={editing?.password ?? ''} onChange={event => setEditing(prev => prev ? { ...prev, password: event.target.value } : prev)} /></div><div className="lc-field"><label className="lc-label">数据库 / DB Index</label><input className="lc-input" value={editing?.database ?? ''} onChange={event => setEditing(prev => prev ? { ...prev, database: event.target.value } : prev)} /></div></>}</Modal>
  </PageShell>;
}
