import assert from 'node:assert/strict';
import { build } from 'esbuild';
const compiled = await build({ entryPoints: ['src/modules/erp/components/erpCsv.ts'], bundle: true, write: false, format: 'esm' });
const { parseCsv, prepareCsv, importFields } = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
assert.deepEqual(parseCsv('\ufeffSKU,名称\r\n001,"商品,含逗号"\r\n002,"多行\r\n名称与""引号"""\r\n'), [['SKU', '名称'], ['001', '商品,含逗号'], ['002', '多行\r\n名称与"引号"']]);
assert.throws(() => parseCsv('name\n"open'), /未闭合/);
assert.throws(() => parseCsv('name\n"closed"junk'), /引号后/);
assert.throws(() => prepareCsv('products', '名称\n测试'), /必填列/);
assert.throws(() => prepareCsv('products', 'sku,SKU,name,category\na,b,c,d'), /重复字段/);
assert.throws(() => prepareCsv('products', 'SKU,名称,分类,非法列\na,b,c,d'), /无法识别列/);
const product = prepareCsv('products', 'SKU,名称,分类,单价,库存,状态\n00001,测试,办公,19.90,2,上架')[0];
assert.deepEqual(product.errors, []);
assert.deepEqual(product.data, { sku: '00001', name: '测试', category: '办公', unit_price: 19.9, stock: 2, status: 'on_sale' });
assert(prepareCsv('products', 'sku,name,category,stock,unit_price\na,b,c,1.5,-10')[0].errors.length === 2);
assert(prepareCsv('products', 'sku,name,category\na,b,c\na,d,e')[1].errors.includes('文件内 SKU 重复'));
assert(prepareCsv('products', 'sku,name,category,status\na,b,c,无效状态')[0].errors.length);
const order = prepareCsv('orders', '订单号,客户,金额,件数,状态,时间\n旧编号,客户甲,100,2,待付款,2026-09-21T09:30')[0];
assert.deepEqual(order.errors, []); assert.equal(order.data.order_date, '2026-09-21 09:30:00'); assert(!('order_no' in order.data));
assert(prepareCsv('orders', '客户,金额,件数,时间\na,0,1,2026-02-30')[0].errors.length);
assert(prepareCsv('orders', '客户,金额,件数,时间\na,0,1,2026-01-01 25:00:00')[0].errors.length);
assert.equal(prepareCsv('suppliers', '名称,电话\n供应商,0012345678')[0].data.phone, '0012345678');
assert.equal(prepareCsv('inventory', 'SKU,方向,数量\nSKU-1,出库,3')[0].data.type, 'out');
assert(prepareCsv('inventory', 'SKU,方向,数量\nSKU-1,入库,0')[0].errors.length);
assert(prepareCsv('inventory', 'SKU,方向,数量\nSKU-1,入库,2147483648')[0].errors.length);
assert.equal(prepareCsv('finance', '类型,金额,分类,时间\n收入,12.50,销售,2026-09-21')[0].data.record_type, 'income');
assert.equal(Object.keys(importFields).length, 7);
assert.throws(() => prepareCsv('customers', '名称\n' + Array(501).fill('客户').join('\n')), /500/);
console.log('CSV quoting, BOM, aliases, required fields, enums, duplicate SKUs, numbers, dates and limits passed.');
