import { formatOaValue, oaFieldOptions } from './oaLabels';
import { useCallback, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import AdminLayout from '../../../components/AdminLayout';
import PageHeader from '../../../components/PageHeader';
import { toast } from '../../../lib/localizedToast';
import { oaApi } from '../api';

type Row = Record<string, unknown> & { id?: number };
const fields: Record<string,string[]> = {
 approval:['approval_no','approval_type','title','status','current_node','submitted_at'], attendance:['attendance_date','check_in','check_out','status','remark'], notices:['title','notice_type','status','is_top','published_at'], schedule:['title','start_time','end_time','schedule_type','location'], org:['name','parent_id','leader_id','member_count']
};
const labels: Record<string,string> = {approval_no:'申请编号',approval_type:'类型',title:'标题',status:'状态',current_node:'当前节点',submitted_at:'提交时间',attendance_date:'日期',check_in:'上班打卡',check_out:'下班打卡',remark:'备注',notice_type:'公告类型',is_top:'置顶',published_at:'发布时间',start_time:'开始时间',end_time:'结束时间',schedule_type:'日程类型',location:'地点',name:'部门名称',parent_id:'上级部门',leader_id:'负责人',member_count:'成员数'};
export default function OaPage({resource,title}:{resource:string;title:string}) {
 const [rows,setRows]=useState<Row[]>([]); const [editing,setEditing]=useState<Row|null>(null); const [form,setForm]=useState<Row>({}); const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{setRows(await oaApi.list(resource));}catch(e){toast.error(e instanceof Error?e.message:'加载失败');}},[resource]); useEffect(()=>{void load();},[load]);
 const save=async()=>{setBusy(true);try{if(editing?.id)await oaApi.update(resource,editing.id,form);else await oaApi.create(resource,form);setEditing(null);setForm({});await load();toast.success('保存成功');}catch(e){toast.error(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}};
 const remove=async(id:number)=>{if(!confirm('确认删除？'))return;try{await oaApi.remove(resource,id);await load();}catch(e){toast.error(e instanceof Error?e.message:'删除失败');}};
 const punch=async(type:'in'|'out')=>{try{await oaApi.create('attendance',{type});await load();toast.success('打卡成功');}catch(e){toast.error(e instanceof Error?e.message:'打卡失败');}};
 const modal = editing ? <div className="oa-modal" role="dialog" aria-modal="true"><div className="oa-dialog"><h3>{editing.id?'编辑':'新增'}{title}</h3>{(fields[resource]||[]).filter(f=>!['id','status','member_count','approval_no','submitted_at','published_at'].includes(f)).map(f=><label key={f}>{labels[f]||f}{oaFieldOptions[f] ? <select value={String(form[f]??'')} onChange={e=>setForm(v=>({...v,[f]:f==='is_top'?Number(e.target.value):e.target.value}))}><option value="" disabled>请选择</option>{form[f]!=null&&!oaFieldOptions[f][String(form[f])]&&<option value={String(form[f])}>{String(form[f])}</option>}{Object.entries(oaFieldOptions[f]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select> : <input value={String(form[f]??'')} onChange={e=>setForm(v=>({...v,[f]:e.target.value}))}/ >}</label>)}<div className="oa-actions"><button className="oa-btn secondary" onClick={()=>setEditing(null)}>取消</button><button className="oa-btn" disabled={busy} onClick={()=>void save()}>保存</button></div></div></div> : null;
 return <AdminLayout><PageHeader title={title} actions={<div className="oa-toolbar">{resource==='attendance'&&<><button className="oa-btn" onClick={()=>void punch('in')}>上班打卡</button><button className="oa-btn" onClick={()=>void punch('out')}>下班打卡</button></>}<button className="oa-btn" onClick={()=>{setEditing({});setForm({});}}>新增</button></div>}/><div className="oa-card"><div className="oa-table-wrap"><table><thead><tr>{(fields[resource]||[]).map(f=><th key={f}>{labels[f]||f}</th>)}<th>操作</th></tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}>{(fields[resource]||[]).map(f=><td key={f}>{formatOaValue(resource,f,r[f])}</td>)}<td>{r.id&&<><button className="oa-link" onClick={()=>{setEditing(r);setForm({...r});}}>编辑</button><button className="oa-link danger" onClick={()=>void remove(Number(r.id))}>删除</button></>}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="oa-empty">暂无数据</div>}</div>{modal&&createPortal(modal, document.body)}<style>{`.oa-toolbar{display:flex;flex-wrap:wrap;gap:8px}.oa-card{overflow:hidden;background:var(--card);border:1px solid var(--border);border-radius:12px;padding:16px}.oa-table-wrap{overflow-x:auto}.oa-card table{width:100%;min-width:720px;border-collapse:collapse}.oa-card th,.oa-card td{padding:10px;border-bottom:1px solid var(--border);text-align:left;white-space:nowrap}.oa-btn{background:var(--primary);color:var(--primary-foreground);border:0;border-radius:7px;padding:8px 14px;cursor:pointer}.oa-btn.secondary{background:var(--secondary);color:var(--secondary-foreground)}.oa-link{border:0;background:none;color:var(--primary);margin-right:8px;cursor:pointer}.oa-link.danger{color:var(--destructive)}.oa-empty{text-align:center;padding:30px;color:var(--muted-foreground)}.oa-modal{position:fixed;inset:0;background:#0006;display:grid;place-items:center;z-index:1000;padding:16px}.oa-dialog{background:var(--card);padding:20px;border-radius:12px;width:min(560px,100%);max-height:calc(100vh - 32px);overflow:auto;box-shadow:0 20px 60px #0004}.oa-dialog h3{margin:0 0 18px;color:var(--foreground);font-size:18px}.oa-dialog label{display:block;margin:0 0 14px;color:var(--muted-foreground);font-size:13px}.oa-dialog input,.oa-dialog select{display:block;width:100%;height:36px;box-sizing:border-box;padding:0 10px;margin-top:6px;border:1px solid var(--input);border-radius:7px;background:var(--background);color:var(--foreground);outline:none}.oa-dialog input:focus,.oa-dialog select:focus{border-color:var(--ring);box-shadow:0 0 0 3px color-mix(in srgb,var(--ring) 25%,transparent)}.oa-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}`}</style></AdminLayout>;
}
